// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAdministrationLabs.Models;

#nullable disable

namespace eAdministrationLabs.Migrations
{
    [DbContext(typeof(EAdministrationLabsContext))]
    [Migration("20241206014330_EditId")]
    partial class EditId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eAdministrationLabs.Models.EquiLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquiLabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__EquiLabs__80AC09911AF6FCC0");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.ToTable("EquiLabs");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEquipment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Equipmen__34474599C099BD7A");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.HistoryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int>("StatusRequestId")
                        .HasColumnType("int")
                        .HasColumnName("StatusRequestID");

                    b.HasKey("Id")
                        .HasName("PK__HistoryR__4D7B4ADD9C22A41E");

                    b.HasIndex("RequestId");

                    b.HasIndex("StatusRequestId");

                    b.ToTable("HistoryRequests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StatusLabId")
                        .HasColumnType("int")
                        .HasColumnName("StatusLabID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Labs__EDBD773AFD35145D");

                    b.HasIndex("StatusLabId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.LabUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__LabUsage__5E5499A891CDA483");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.ToTable("LabUsageLogs");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unread");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__20CF2E327F781F3A");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<int>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Requests__33A8519A2D96C229");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ImageId");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.RequestImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id")
                        .HasName("PK__RequestI__7516F4EC9B4E4FB6");

                    b.ToTable("RequestImages");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__8AFACE3A12AC46C2");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SoftwareID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("LabID");

                    b.Property<string>("License")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Free");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Software__25EDB8DC784E20C8");

                    b.HasIndex("LabId");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.StatusLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusLabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__StatusLa__072A22DFBE90E538");

                    b.ToTable("StatusLabs");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.StatusRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__StatusRe__B62FB50E9DBB1A7F");

                    b.ToTable("StatusRequests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Users__1788CCACD9780C3D");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053471AAC870")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_Users_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("eAdministrationLabs.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3D978A55F8AEFCEB");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.EquiLab", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Equipment", "Equipment")
                        .WithMany("EquiLabs")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__EquiLabs__Equipm__4BAC3F29");

                    b.HasOne("eAdministrationLabs.Models.Lab", "Lab")
                        .WithMany("EquiLabs")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__EquiLabs__LabID__4CA06362");

                    b.HasOne("eAdministrationLabs.Models.User", "User")
                        .WithMany("EquiLabs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__EquiLabs__UserID__4D94879B");

                    b.Navigation("Equipment");

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.HistoryRequest", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Request", "Request")
                        .WithMany("HistoryRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HistoryRe__Reque__68487DD7");

                    b.HasOne("eAdministrationLabs.Models.StatusRequest", "StatusRequest")
                        .WithMany("HistoryRequests")
                        .HasForeignKey("StatusRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HistoryRe__Statu__693CA210");

                    b.Navigation("Request");

                    b.Navigation("StatusRequest");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Lab", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.StatusLab", "StatusLab")
                        .WithMany("Labs")
                        .HasForeignKey("StatusLabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Labs__StatusLabI__45F365D3");

                    b.Navigation("StatusLab");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.LabUsageLog", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Lab", "Lab")
                        .WithMany("LabUsageLogs")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LabUsageL__LabID__5812160E");

                    b.HasOne("eAdministrationLabs.Models.User", "User")
                        .WithMany("LabUsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LabUsageL__UserI__59063A47");

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Notification", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__6EF57B66");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Request", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Equipment", "Equipment")
                        .WithMany("Requests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Requests__Equipm__6383C8BA");

                    b.HasOne("eAdministrationLabs.Models.RequestImage", "Image")
                        .WithMany("Requests")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Requests__ImageI__6477ECF3");

                    b.HasOne("eAdministrationLabs.Models.Lab", "Lab")
                        .WithMany("Requests")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Requests__LabID__628FA481");

                    b.HasOne("eAdministrationLabs.Models.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Requests__UserID__619B8048");

                    b.Navigation("Equipment");

                    b.Navigation("Image");

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Software", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Lab", "Lab")
                        .WithMany("Softwares")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Softwares__LabID__5441852A");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.UserRole", b =>
                {
                    b.HasOne("eAdministrationLabs.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__412EB0B6");

                    b.HasOne("eAdministrationLabs.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__403A8C7D");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Equipment", b =>
                {
                    b.Navigation("EquiLabs");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Lab", b =>
                {
                    b.Navigation("EquiLabs");

                    b.Navigation("LabUsageLogs");

                    b.Navigation("Requests");

                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Request", b =>
                {
                    b.Navigation("HistoryRequests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.RequestImage", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.StatusLab", b =>
                {
                    b.Navigation("Labs");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.StatusRequest", b =>
                {
                    b.Navigation("HistoryRequests");
                });

            modelBuilder.Entity("eAdministrationLabs.Models.User", b =>
                {
                    b.Navigation("EquiLabs");

                    b.Navigation("LabUsageLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Requests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
